package br.com.dev.superheroes.infra.model

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable

@DynamoDBTable(tableName = "superhero")
data class Hero(
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    var id: String? = null,
    @DynamoDBAttribute
    var name: String? = null,
    @DynamoDBAttribute
    var enabled: Boolean? = null
)